/*
 * This file is generated by jOOQ.
 */
package nl.overheid.aerius.emissionservice.jooq.template.tables;


import nl.overheid.aerius.emissionservice.jooq.template.Template;
import nl.overheid.aerius.emissionservice.jooq.template.tables.records.FarmLodgingFodderMeasureReductionFactorsViewRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row11;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * Geeft de eigenschappen van een voer- en managementmaatregel, inclusief 
 * code, beschrijving, de diercategorieën waarop deze mag worden toegepast 
 * en de bijbehorende aandeel- en reductiefactoren voor die diercategorie.
 * 
 * 
 * @file source/database/src/main/sql/emission_factors/04-views/farms.sql
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FarmLodgingFodderMeasureReductionFactorsView extends TableImpl<FarmLodgingFodderMeasureReductionFactorsViewRecord> {

    private static final long serialVersionUID = -722186873;

    /**
     * The reference instance of <code>template.farm_lodging_fodder_measure_reduction_factors_view</code>
     */
    public static final FarmLodgingFodderMeasureReductionFactorsView FARM_LODGING_FODDER_MEASURE_REDUCTION_FACTORS_VIEW = new FarmLodgingFodderMeasureReductionFactorsView();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FarmLodgingFodderMeasureReductionFactorsViewRecord> getRecordType() {
        return FarmLodgingFodderMeasureReductionFactorsViewRecord.class;
    }

    /**
     * The column <code>template.farm_lodging_fodder_measure_reduction_factors_view.farm_lodging_fodder_measure_id</code>.
     */
    public final TableField<FarmLodgingFodderMeasureReductionFactorsViewRecord, Integer> FARM_LODGING_FODDER_MEASURE_ID = createField(DSL.name("farm_lodging_fodder_measure_id"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>template.farm_lodging_fodder_measure_reduction_factors_view.code</code>.
     */
    public final TableField<FarmLodgingFodderMeasureReductionFactorsViewRecord, String> CODE = createField(DSL.name("code"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>template.farm_lodging_fodder_measure_reduction_factors_view.name</code>.
     */
    public final TableField<FarmLodgingFodderMeasureReductionFactorsViewRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>template.farm_lodging_fodder_measure_reduction_factors_view.description</code>.
     */
    public final TableField<FarmLodgingFodderMeasureReductionFactorsViewRecord, String> DESCRIPTION = createField(DSL.name("description"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>template.farm_lodging_fodder_measure_reduction_factors_view.farm_animal_category_id</code>.
     */
    public final TableField<FarmLodgingFodderMeasureReductionFactorsViewRecord, Integer> FARM_ANIMAL_CATEGORY_ID = createField(DSL.name("farm_animal_category_id"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>template.farm_lodging_fodder_measure_reduction_factors_view.substance_id</code>.
     */
    public final TableField<FarmLodgingFodderMeasureReductionFactorsViewRecord, Short> SUBSTANCE_ID = createField(DSL.name("substance_id"), org.jooq.impl.SQLDataType.SMALLINT, this, "");

    /**
     * The column <code>template.farm_lodging_fodder_measure_reduction_factors_view.reduction_factor_floor</code>.
     */
    public final TableField<FarmLodgingFodderMeasureReductionFactorsViewRecord, Float> REDUCTION_FACTOR_FLOOR = createField(DSL.name("reduction_factor_floor"), org.jooq.impl.SQLDataType.REAL, this, "");

    /**
     * The column <code>template.farm_lodging_fodder_measure_reduction_factors_view.reduction_factor_cellar</code>.
     */
    public final TableField<FarmLodgingFodderMeasureReductionFactorsViewRecord, Float> REDUCTION_FACTOR_CELLAR = createField(DSL.name("reduction_factor_cellar"), org.jooq.impl.SQLDataType.REAL, this, "");

    /**
     * The column <code>template.farm_lodging_fodder_measure_reduction_factors_view.reduction_factor_total</code>.
     */
    public final TableField<FarmLodgingFodderMeasureReductionFactorsViewRecord, Float> REDUCTION_FACTOR_TOTAL = createField(DSL.name("reduction_factor_total"), org.jooq.impl.SQLDataType.REAL, this, "");

    /**
     * The column <code>template.farm_lodging_fodder_measure_reduction_factors_view.proportion_floor</code>.
     */
    public final TableField<FarmLodgingFodderMeasureReductionFactorsViewRecord, Float> PROPORTION_FLOOR = createField(DSL.name("proportion_floor"), org.jooq.impl.SQLDataType.REAL, this, "");

    /**
     * The column <code>template.farm_lodging_fodder_measure_reduction_factors_view.proportion_cellar</code>.
     */
    public final TableField<FarmLodgingFodderMeasureReductionFactorsViewRecord, Float> PROPORTION_CELLAR = createField(DSL.name("proportion_cellar"), org.jooq.impl.SQLDataType.REAL, this, "");

    /**
     * Create a <code>template.farm_lodging_fodder_measure_reduction_factors_view</code> table reference
     */
    public FarmLodgingFodderMeasureReductionFactorsView() {
        this(DSL.name("farm_lodging_fodder_measure_reduction_factors_view"), null);
    }

    /**
     * Create an aliased <code>template.farm_lodging_fodder_measure_reduction_factors_view</code> table reference
     */
    public FarmLodgingFodderMeasureReductionFactorsView(String alias) {
        this(DSL.name(alias), FARM_LODGING_FODDER_MEASURE_REDUCTION_FACTORS_VIEW);
    }

    /**
     * Create an aliased <code>template.farm_lodging_fodder_measure_reduction_factors_view</code> table reference
     */
    public FarmLodgingFodderMeasureReductionFactorsView(Name alias) {
        this(alias, FARM_LODGING_FODDER_MEASURE_REDUCTION_FACTORS_VIEW);
    }

    private FarmLodgingFodderMeasureReductionFactorsView(Name alias, Table<FarmLodgingFodderMeasureReductionFactorsViewRecord> aliased) {
        this(alias, aliased, null);
    }

    private FarmLodgingFodderMeasureReductionFactorsView(Name alias, Table<FarmLodgingFodderMeasureReductionFactorsViewRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Geeft de eigenschappen van een voer- en managementmaatregel, inclusief code, beschrijving, de diercategorieën waarop deze mag worden toegepast en de bijbehorende aandeel- en reductiefactoren voor die diercategorie.\r\n\r\n@file source/database/src/main/sql/emission_factors/04-views/farms.sql"), TableOptions.view("create view \"farm_lodging_fodder_measure_reduction_factors_view\" as  SELECT farm_lodging_fodder_measures.farm_lodging_fodder_measure_id,\n    farm_lodging_fodder_measures.code,\n    farm_lodging_fodder_measures.name,\n    farm_lodging_fodder_measures.description,\n    farm_lodging_fodder_measures_animal_category.farm_animal_category_id,\n    farm_lodging_fodder_measure_reduction_factors.substance_id,\n    farm_lodging_fodder_measure_reduction_factors.reduction_factor_floor,\n    farm_lodging_fodder_measure_reduction_factors.reduction_factor_cellar,\n    farm_lodging_fodder_measure_reduction_factors.reduction_factor_total,\n    farm_lodging_fodder_measures_animal_category.proportion_floor,\n    farm_lodging_fodder_measures_animal_category.proportion_cellar\n   FROM (((template.farm_lodging_fodder_measures\n     JOIN template.farm_lodging_fodder_measure_reduction_factors USING (farm_lodging_fodder_measure_id))\n     JOIN template.farm_lodging_fodder_measures_animal_category USING (farm_lodging_fodder_measure_id))\n     JOIN template.farm_animal_categories USING (farm_animal_category_id));"));
    }

    public <O extends Record> FarmLodgingFodderMeasureReductionFactorsView(Table<O> child, ForeignKey<O, FarmLodgingFodderMeasureReductionFactorsViewRecord> key) {
        super(child, key, FARM_LODGING_FODDER_MEASURE_REDUCTION_FACTORS_VIEW);
    }

    @Override
    public Schema getSchema() {
        return Template.TEMPLATE;
    }

    @Override
    public FarmLodgingFodderMeasureReductionFactorsView as(String alias) {
        return new FarmLodgingFodderMeasureReductionFactorsView(DSL.name(alias), this);
    }

    @Override
    public FarmLodgingFodderMeasureReductionFactorsView as(Name alias) {
        return new FarmLodgingFodderMeasureReductionFactorsView(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FarmLodgingFodderMeasureReductionFactorsView rename(String name) {
        return new FarmLodgingFodderMeasureReductionFactorsView(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FarmLodgingFodderMeasureReductionFactorsView rename(Name name) {
        return new FarmLodgingFodderMeasureReductionFactorsView(name, null);
    }

    // -------------------------------------------------------------------------
    // Row11 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row11<Integer, String, String, String, Integer, Short, Float, Float, Float, Float, Float> fieldsRow() {
        return (Row11) super.fieldsRow();
    }
}
