/*
 * This file is generated by jOOQ.
 */
package nl.overheid.aerius.emissionservice.jooq.template.tables;


import java.util.Arrays;
import java.util.List;

import nl.overheid.aerius.emissionservice.jooq.template.Keys;
import nl.overheid.aerius.emissionservice.jooq.template.Template;
import nl.overheid.aerius.emissionservice.jooq.template.tables.records.FarmLodgingTypesToReductiveLodgingSystemsRecord;

import org.jooq.Check;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


/**
 * Koppeling (N:N) welke aangeeft op welke stalsystemen de emissiereducerende 
 * staltechnieken gestapeld kunnen worden.
 * In deze tabel staan de toegestane combinaties van stapelingen binnen de 
 * RAV systematiek, echter binnen de Nb-wet is iedere combinatie mogelijk.
 * 
 * 
 * @file source/database/src/main/sql/emission_factors/02-tables/farms.sql
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FarmLodgingTypesToReductiveLodgingSystems extends TableImpl<FarmLodgingTypesToReductiveLodgingSystemsRecord> {

    private static final long serialVersionUID = 549409147;

    /**
     * The reference instance of <code>template.farm_lodging_types_to_reductive_lodging_systems</code>
     */
    public static final FarmLodgingTypesToReductiveLodgingSystems FARM_LODGING_TYPES_TO_REDUCTIVE_LODGING_SYSTEMS = new FarmLodgingTypesToReductiveLodgingSystems();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FarmLodgingTypesToReductiveLodgingSystemsRecord> getRecordType() {
        return FarmLodgingTypesToReductiveLodgingSystemsRecord.class;
    }

    /**
     * The column <code>template.farm_lodging_types_to_reductive_lodging_systems.farm_lodging_type_id</code>.
     */
    public final TableField<FarmLodgingTypesToReductiveLodgingSystemsRecord, Integer> FARM_LODGING_TYPE_ID = createField(DSL.name("farm_lodging_type_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>template.farm_lodging_types_to_reductive_lodging_systems.farm_reductive_lodging_system_id</code>.
     */
    public final TableField<FarmLodgingTypesToReductiveLodgingSystemsRecord, Integer> FARM_REDUCTIVE_LODGING_SYSTEM_ID = createField(DSL.name("farm_reductive_lodging_system_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>template.farm_lodging_types_to_reductive_lodging_systems</code> table reference
     */
    public FarmLodgingTypesToReductiveLodgingSystems() {
        this(DSL.name("farm_lodging_types_to_reductive_lodging_systems"), null);
    }

    /**
     * Create an aliased <code>template.farm_lodging_types_to_reductive_lodging_systems</code> table reference
     */
    public FarmLodgingTypesToReductiveLodgingSystems(String alias) {
        this(DSL.name(alias), FARM_LODGING_TYPES_TO_REDUCTIVE_LODGING_SYSTEMS);
    }

    /**
     * Create an aliased <code>template.farm_lodging_types_to_reductive_lodging_systems</code> table reference
     */
    public FarmLodgingTypesToReductiveLodgingSystems(Name alias) {
        this(alias, FARM_LODGING_TYPES_TO_REDUCTIVE_LODGING_SYSTEMS);
    }

    private FarmLodgingTypesToReductiveLodgingSystems(Name alias, Table<FarmLodgingTypesToReductiveLodgingSystemsRecord> aliased) {
        this(alias, aliased, null);
    }

    private FarmLodgingTypesToReductiveLodgingSystems(Name alias, Table<FarmLodgingTypesToReductiveLodgingSystemsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Koppeling (N:N) welke aangeeft op welke stalsystemen de emissiereducerende staltechnieken gestapeld kunnen worden.\r\nIn deze tabel staan de toegestane combinaties van stapelingen binnen de RAV systematiek, echter binnen de Nb-wet is iedere combinatie mogelijk.\r\n\r\n@file source/database/src/main/sql/emission_factors/02-tables/farms.sql"), TableOptions.table());
    }

    public <O extends Record> FarmLodgingTypesToReductiveLodgingSystems(Table<O> child, ForeignKey<O, FarmLodgingTypesToReductiveLodgingSystemsRecord> key) {
        super(child, key, FARM_LODGING_TYPES_TO_REDUCTIVE_LODGING_SYSTEMS);
    }

    @Override
    public Schema getSchema() {
        return Template.TEMPLATE;
    }

    @Override
    public UniqueKey<FarmLodgingTypesToReductiveLodgingSystemsRecord> getPrimaryKey() {
        return Keys.FARM_LODGING_TYPES_TO_REDUCTIVE_LODGING_SYSTEMS_PKEY;
    }

    @Override
    public List<UniqueKey<FarmLodgingTypesToReductiveLodgingSystemsRecord>> getKeys() {
        return Arrays.<UniqueKey<FarmLodgingTypesToReductiveLodgingSystemsRecord>>asList(Keys.FARM_LODGING_TYPES_TO_REDUCTIVE_LODGING_SYSTEMS_PKEY);
    }

    @Override
    public List<ForeignKey<FarmLodgingTypesToReductiveLodgingSystemsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<FarmLodgingTypesToReductiveLodgingSystemsRecord, ?>>asList(Keys.FARM_LODGING_TYPES_TO_REDUCTIVE_LODGING_SYSTEMS__FARM_LODGING_TYPES_TO_REDUCTIVE_LODGING_SYSTEMS_FKEY_TYPES, Keys.FARM_LODGING_TYPES_TO_REDUCTIVE_LODGING_SYSTEMS__FARM_LODGING_TYPES_TO_REDUCTIVE_LODGING_SYSTEMS_FKEY_REDUCTIVE);
    }

    public FarmLodgingTypes farmLodgingTypes() {
        return new FarmLodgingTypes(this, Keys.FARM_LODGING_TYPES_TO_REDUCTIVE_LODGING_SYSTEMS__FARM_LODGING_TYPES_TO_REDUCTIVE_LODGING_SYSTEMS_FKEY_TYPES);
    }

    public FarmReductiveLodgingSystems farmReductiveLodgingSystems() {
        return new FarmReductiveLodgingSystems(this, Keys.FARM_LODGING_TYPES_TO_REDUCTIVE_LODGING_SYSTEMS__FARM_LODGING_TYPES_TO_REDUCTIVE_LODGING_SYSTEMS_FKEY_REDUCTIVE);
    }

    @Override
    public List<Check<FarmLodgingTypesToReductiveLodgingSystemsRecord>> getChecks() {
        return Arrays.<Check<FarmLodgingTypesToReductiveLodgingSystemsRecord>>asList(
              Internal.createCheck(this, DSL.name("farm_lodging_types_to_reductive_lodging_systems_chk_selfref"), "((farm_lodging_type_id <> farm_reductive_lodging_system_id))", true)
        );
    }

    @Override
    public FarmLodgingTypesToReductiveLodgingSystems as(String alias) {
        return new FarmLodgingTypesToReductiveLodgingSystems(DSL.name(alias), this);
    }

    @Override
    public FarmLodgingTypesToReductiveLodgingSystems as(Name alias) {
        return new FarmLodgingTypesToReductiveLodgingSystems(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FarmLodgingTypesToReductiveLodgingSystems rename(String name) {
        return new FarmLodgingTypesToReductiveLodgingSystems(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FarmLodgingTypesToReductiveLodgingSystems rename(Name name) {
        return new FarmLodgingTypesToReductiveLodgingSystems(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
