/*
 * This file is generated by jOOQ.
 */
package nl.overheid.aerius.emissionservice.jooq.template.tables;


import java.util.Arrays;
import java.util.List;

import nl.overheid.aerius.emissionservice.jooq.i18n.enums.LanguageCodeType;
import nl.overheid.aerius.emissionservice.jooq.template.Keys;
import nl.overheid.aerius.emissionservice.jooq.template.Template;
import nl.overheid.aerius.emissionservice.jooq.template.tables.records.I18nShippingInlandWaterwayCategoriesRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * Vertaaltabel voor categorieën van verschillende soorten binnenvaart vaarwegen.
 * 
 * 
 * @file source/database/src/main/sql/emission_factors/i18n/shipping_inland.sql
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class I18nShippingInlandWaterwayCategories extends TableImpl<I18nShippingInlandWaterwayCategoriesRecord> {

    private static final long serialVersionUID = -2047872117;

    /**
     * The reference instance of <code>template.i18n_shipping_inland_waterway_categories</code>
     */
    public static final I18nShippingInlandWaterwayCategories I18N_SHIPPING_INLAND_WATERWAY_CATEGORIES = new I18nShippingInlandWaterwayCategories();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<I18nShippingInlandWaterwayCategoriesRecord> getRecordType() {
        return I18nShippingInlandWaterwayCategoriesRecord.class;
    }

    /**
     * The column <code>template.i18n_shipping_inland_waterway_categories.shipping_inland_waterway_category_id</code>.
     */
    public final TableField<I18nShippingInlandWaterwayCategoriesRecord, Short> SHIPPING_INLAND_WATERWAY_CATEGORY_ID = createField(DSL.name("shipping_inland_waterway_category_id"), org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>template.i18n_shipping_inland_waterway_categories.language_code</code>.
     */
    public final TableField<I18nShippingInlandWaterwayCategoriesRecord, LanguageCodeType> LANGUAGE_CODE = createField(DSL.name("language_code"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false).asEnumDataType(nl.overheid.aerius.emissionservice.jooq.i18n.enums.LanguageCodeType.class), this, "");

    /**
     * The column <code>template.i18n_shipping_inland_waterway_categories.name</code>.
     */
    public final TableField<I18nShippingInlandWaterwayCategoriesRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>template.i18n_shipping_inland_waterway_categories.description</code>.
     */
    public final TableField<I18nShippingInlandWaterwayCategoriesRecord, String> DESCRIPTION = createField(DSL.name("description"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>template.i18n_shipping_inland_waterway_categories</code> table reference
     */
    public I18nShippingInlandWaterwayCategories() {
        this(DSL.name("i18n_shipping_inland_waterway_categories"), null);
    }

    /**
     * Create an aliased <code>template.i18n_shipping_inland_waterway_categories</code> table reference
     */
    public I18nShippingInlandWaterwayCategories(String alias) {
        this(DSL.name(alias), I18N_SHIPPING_INLAND_WATERWAY_CATEGORIES);
    }

    /**
     * Create an aliased <code>template.i18n_shipping_inland_waterway_categories</code> table reference
     */
    public I18nShippingInlandWaterwayCategories(Name alias) {
        this(alias, I18N_SHIPPING_INLAND_WATERWAY_CATEGORIES);
    }

    private I18nShippingInlandWaterwayCategories(Name alias, Table<I18nShippingInlandWaterwayCategoriesRecord> aliased) {
        this(alias, aliased, null);
    }

    private I18nShippingInlandWaterwayCategories(Name alias, Table<I18nShippingInlandWaterwayCategoriesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Vertaaltabel voor categorieën van verschillende soorten binnenvaart vaarwegen.\r\n\r\n@file source/database/src/main/sql/emission_factors/i18n/shipping_inland.sql"), TableOptions.table());
    }

    public <O extends Record> I18nShippingInlandWaterwayCategories(Table<O> child, ForeignKey<O, I18nShippingInlandWaterwayCategoriesRecord> key) {
        super(child, key, I18N_SHIPPING_INLAND_WATERWAY_CATEGORIES);
    }

    @Override
    public Schema getSchema() {
        return Template.TEMPLATE;
    }

    @Override
    public UniqueKey<I18nShippingInlandWaterwayCategoriesRecord> getPrimaryKey() {
        return Keys.I18N_SHIPPING_INLAND_WATERWAY_CATEGORIES_PKEY;
    }

    @Override
    public List<UniqueKey<I18nShippingInlandWaterwayCategoriesRecord>> getKeys() {
        return Arrays.<UniqueKey<I18nShippingInlandWaterwayCategoriesRecord>>asList(Keys.I18N_SHIPPING_INLAND_WATERWAY_CATEGORIES_PKEY);
    }

    @Override
    public List<ForeignKey<I18nShippingInlandWaterwayCategoriesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<I18nShippingInlandWaterwayCategoriesRecord, ?>>asList(Keys.I18N_SHIPPING_INLAND_WATERWAY_CATEGORIES__I18N_SHIPPING_INLAND_WATERWAY_CATEGORIES_FKEY);
    }

    public ShippingInlandWaterwayCategories shippingInlandWaterwayCategories() {
        return new ShippingInlandWaterwayCategories(this, Keys.I18N_SHIPPING_INLAND_WATERWAY_CATEGORIES__I18N_SHIPPING_INLAND_WATERWAY_CATEGORIES_FKEY);
    }

    @Override
    public I18nShippingInlandWaterwayCategories as(String alias) {
        return new I18nShippingInlandWaterwayCategories(DSL.name(alias), this);
    }

    @Override
    public I18nShippingInlandWaterwayCategories as(Name alias) {
        return new I18nShippingInlandWaterwayCategories(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public I18nShippingInlandWaterwayCategories rename(String name) {
        return new I18nShippingInlandWaterwayCategories(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public I18nShippingInlandWaterwayCategories rename(Name name) {
        return new I18nShippingInlandWaterwayCategories(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Short, LanguageCodeType, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
