/*
 * This file is generated by jOOQ.
 */
package nl.overheid.aerius.emissionservice.jooq.template.tables;


import java.util.Arrays;
import java.util.List;

import nl.overheid.aerius.emissionservice.jooq.template.Keys;
import nl.overheid.aerius.emissionservice.jooq.template.Template;
import nl.overheid.aerius.emissionservice.jooq.template.tables.records.SectorsMainGcnSectorRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * Koppeltabel om voor de sectoren (zonder (sub)categorieen) aan te geven 
 * aan welke hoofd-GCN-sector deze bronnen gekoppeld kunnen worden.
 * 
 * @file source/database/src/main/sql/sectors/02-tables/01-sectors.sql
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SectorsMainGcnSector extends TableImpl<SectorsMainGcnSectorRecord> {

    private static final long serialVersionUID = 1001806099;

    /**
     * The reference instance of <code>template.sectors_main_gcn_sector</code>
     */
    public static final SectorsMainGcnSector SECTORS_MAIN_GCN_SECTOR = new SectorsMainGcnSector();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SectorsMainGcnSectorRecord> getRecordType() {
        return SectorsMainGcnSectorRecord.class;
    }

    /**
     * The column <code>template.sectors_main_gcn_sector.sector_id</code>.
     */
    public final TableField<SectorsMainGcnSectorRecord, Integer> SECTOR_ID = createField(DSL.name("sector_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>template.sectors_main_gcn_sector.gcn_sector_id</code>.
     */
    public final TableField<SectorsMainGcnSectorRecord, Integer> GCN_SECTOR_ID = createField(DSL.name("gcn_sector_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>template.sectors_main_gcn_sector</code> table reference
     */
    public SectorsMainGcnSector() {
        this(DSL.name("sectors_main_gcn_sector"), null);
    }

    /**
     * Create an aliased <code>template.sectors_main_gcn_sector</code> table reference
     */
    public SectorsMainGcnSector(String alias) {
        this(DSL.name(alias), SECTORS_MAIN_GCN_SECTOR);
    }

    /**
     * Create an aliased <code>template.sectors_main_gcn_sector</code> table reference
     */
    public SectorsMainGcnSector(Name alias) {
        this(alias, SECTORS_MAIN_GCN_SECTOR);
    }

    private SectorsMainGcnSector(Name alias, Table<SectorsMainGcnSectorRecord> aliased) {
        this(alias, aliased, null);
    }

    private SectorsMainGcnSector(Name alias, Table<SectorsMainGcnSectorRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Koppeltabel om voor de sectoren (zonder (sub)categorieen) aan te geven aan welke hoofd-GCN-sector deze bronnen gekoppeld kunnen worden.\r\n\r\n@file source/database/src/main/sql/sectors/02-tables/01-sectors.sql"), TableOptions.table());
    }

    public <O extends Record> SectorsMainGcnSector(Table<O> child, ForeignKey<O, SectorsMainGcnSectorRecord> key) {
        super(child, key, SECTORS_MAIN_GCN_SECTOR);
    }

    @Override
    public Schema getSchema() {
        return Template.TEMPLATE;
    }

    @Override
    public UniqueKey<SectorsMainGcnSectorRecord> getPrimaryKey() {
        return Keys.SECTORS_MAIN_GCN_SECTOR_PKEY;
    }

    @Override
    public List<UniqueKey<SectorsMainGcnSectorRecord>> getKeys() {
        return Arrays.<UniqueKey<SectorsMainGcnSectorRecord>>asList(Keys.SECTORS_MAIN_GCN_SECTOR_PKEY);
    }

    @Override
    public List<ForeignKey<SectorsMainGcnSectorRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<SectorsMainGcnSectorRecord, ?>>asList(Keys.SECTORS_MAIN_GCN_SECTOR__SECTORS_MAIN_GCN_SECTOR_FKEY_SECTORS, Keys.SECTORS_MAIN_GCN_SECTOR__SECTORS_MAIN_GCN_SECTOR_FKEY_GCN_SECTORS);
    }

    public Sectors sectors() {
        return new Sectors(this, Keys.SECTORS_MAIN_GCN_SECTOR__SECTORS_MAIN_GCN_SECTOR_FKEY_SECTORS);
    }

    public GcnSectors gcnSectors() {
        return new GcnSectors(this, Keys.SECTORS_MAIN_GCN_SECTOR__SECTORS_MAIN_GCN_SECTOR_FKEY_GCN_SECTORS);
    }

    @Override
    public SectorsMainGcnSector as(String alias) {
        return new SectorsMainGcnSector(DSL.name(alias), this);
    }

    @Override
    public SectorsMainGcnSector as(Name alias) {
        return new SectorsMainGcnSector(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SectorsMainGcnSector rename(String name) {
        return new SectorsMainGcnSector(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SectorsMainGcnSector rename(Name name) {
        return new SectorsMainGcnSector(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
