/*
 * This file is generated by jOOQ.
 */
package nl.overheid.aerius.emissionservice.jooq.public_.routines;


import java.math.BigDecimal;

import nl.overheid.aerius.emissionservice.jooq.public_.Public;
import nl.overheid.aerius.emissionservice.jooq.public_.udt.records.AeKeyValueRsRecord;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AeMaxWithKey extends AbstractRoutine<AeKeyValueRsRecord> {

    private static final long serialVersionUID = 329208840;

    /**
     * The parameter <code>public.ae_max_with_key.RETURN_VALUE</code>.
     */
    public static final Parameter<AeKeyValueRsRecord> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", nl.overheid.aerius.emissionservice.jooq.public_.udt.AeKeyValueRs.AE_KEY_VALUE_RS.getDataType(), false, false);

    /**
     * The parameter <code>public.ae_max_with_key._1</code>.
     */
    public static final Parameter<BigDecimal> _1 = Internal.createParameter("_1", org.jooq.impl.SQLDataType.NUMERIC, false, true);

    /**
     * The parameter <code>public.ae_max_with_key._2</code>.
     */
    public static final Parameter<BigDecimal> _2 = Internal.createParameter("_2", org.jooq.impl.SQLDataType.NUMERIC, false, true);

    /**
     * Create a new routine call instance
     */
    public AeMaxWithKey() {
        super("ae_max_with_key", Public.PUBLIC, nl.overheid.aerius.emissionservice.jooq.public_.udt.AeKeyValueRs.AE_KEY_VALUE_RS.getDataType());

        setReturnParameter(RETURN_VALUE);
        addInParameter(_1);
        addInParameter(_2);
    }

    /**
     * Set the <code>_1</code> parameter IN value to the routine
     */
    public void set__1(BigDecimal value) {
        setValue(_1, value);
    }

    /**
     * Set the <code>_1</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void set__1(Field<BigDecimal> field) {
        setField(_1, field);
    }

    /**
     * Set the <code>_2</code> parameter IN value to the routine
     */
    public void set__2(BigDecimal value) {
        setValue(_2, value);
    }

    /**
     * Set the <code>_2</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void set__2(Field<BigDecimal> field) {
        setField(_2, field);
    }
}
