/*
 * This file is generated by jOOQ.
 */
package nl.overheid.aerius.emissionservice.jooq.public_;


import nl.overheid.aerius.emissionservice.jooq.public_.tables.Constants;
import nl.overheid.aerius.emissionservice.jooq.public_.tables.Substances;
import nl.overheid.aerius.emissionservice.jooq.public_.tables.records.ConstantsRecord;
import nl.overheid.aerius.emissionservice.jooq.public_.tables.records.SubstancesRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ConstantsRecord> CONSTANTS_PKEY = UniqueKeys0.CONSTANTS_PKEY;
    public static final UniqueKey<SubstancesRecord> SUBSTANCES_PKEY = UniqueKeys0.SUBSTANCES_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<ConstantsRecord> CONSTANTS_PKEY = Internal.createUniqueKey(Constants.CONSTANTS, "constants_pkey", new TableField[] { Constants.CONSTANTS.KEY }, true);
        public static final UniqueKey<SubstancesRecord> SUBSTANCES_PKEY = Internal.createUniqueKey(Substances.SUBSTANCES, "substances_pkey", new TableField[] { Substances.SUBSTANCES.SUBSTANCE_ID }, true);
    }
}
