/*
 * This file is generated by jOOQ.
 */
package nl.overheid.aerius.emissionservice.jooq.public_.tables;


import java.util.Arrays;
import java.util.List;

import nl.overheid.aerius.emissionservice.jooq.public_.Keys;
import nl.overheid.aerius.emissionservice.jooq.public_.Public;
import nl.overheid.aerius.emissionservice.jooq.public_.enums.ConstantType;
import nl.overheid.aerius.emissionservice.jooq.public_.tables.records.ConstantsRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * Tabel voor de database constanten.
 * 
 * @file source/database/src/main/sql/essentials/00-init/03-constants.sql
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Constants extends TableImpl<ConstantsRecord> {

    private static final long serialVersionUID = -1210784989;

    /**
     * The reference instance of <code>public.constants</code>
     */
    public static final Constants CONSTANTS = new Constants();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ConstantsRecord> getRecordType() {
        return ConstantsRecord.class;
    }

    /**
     * The column <code>public.constants.key</code>.
     */
    public final TableField<ConstantsRecord, String> KEY = createField(DSL.name("key"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.constants.value</code>.
     */
    public final TableField<ConstantsRecord, String> VALUE = createField(DSL.name("value"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.constants.description</code>.
     */
    public final TableField<ConstantsRecord, String> DESCRIPTION = createField(DSL.name("description"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.constants.type</code>.
     */
    public final TableField<ConstantsRecord, ConstantType> TYPE = createField(DSL.name("type"), org.jooq.impl.SQLDataType.VARCHAR.asEnumDataType(nl.overheid.aerius.emissionservice.jooq.public_.enums.ConstantType.class), this, "");

    /**
     * Create a <code>public.constants</code> table reference
     */
    public Constants() {
        this(DSL.name("constants"), null);
    }

    /**
     * Create an aliased <code>public.constants</code> table reference
     */
    public Constants(String alias) {
        this(DSL.name(alias), CONSTANTS);
    }

    /**
     * Create an aliased <code>public.constants</code> table reference
     */
    public Constants(Name alias) {
        this(alias, CONSTANTS);
    }

    private Constants(Name alias, Table<ConstantsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Constants(Name alias, Table<ConstantsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Tabel voor de database constanten.\r\n\r\n@file source/database/src/main/sql/essentials/00-init/03-constants.sql"), TableOptions.table());
    }

    public <O extends Record> Constants(Table<O> child, ForeignKey<O, ConstantsRecord> key) {
        super(child, key, CONSTANTS);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<ConstantsRecord> getPrimaryKey() {
        return Keys.CONSTANTS_PKEY;
    }

    @Override
    public List<UniqueKey<ConstantsRecord>> getKeys() {
        return Arrays.<UniqueKey<ConstantsRecord>>asList(Keys.CONSTANTS_PKEY);
    }

    @Override
    public Constants as(String alias) {
        return new Constants(DSL.name(alias), this);
    }

    @Override
    public Constants as(Name alias) {
        return new Constants(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Constants rename(String name) {
        return new Constants(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Constants rename(Name name) {
        return new Constants(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, String, ConstantType> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
