/*
 * This file is generated by jOOQ.
 */
package nl.overheid.aerius.emissionservice.jooq.i18n;


import nl.overheid.aerius.emissionservice.jooq.i18n.tables.Messages;
import nl.overheid.aerius.emissionservice.jooq.i18n.tables.SystemInfoMessages;


/**
 * Convenience access to all tables in i18n
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * Systeem tabel voor localized teksten.

@file source/database/src/main/sql/i18n/02-tables.sql
     */
    public static final Messages MESSAGES = Messages.MESSAGES;

    /**
     * Systeem info tabel voor localized teksten, voor tonen van systeem berichten.

@file source/database/src/main/sql/i18n/02-tables.sql
     */
    public static final SystemInfoMessages SYSTEM_INFO_MESSAGES = SystemInfoMessages.SYSTEM_INFO_MESSAGES;
}
