openapi: 3.0.1
info:
  title: AERIUS emission service
  description: 'This is a service to retrieve AERIUS emission factors for different sectors'
  termsOfService: TODO
  contact:
    email: TODO
  license:
    name: GNU Affero General Public License v3.0
    url: https://www.gnu.org/licenses/agpl-3.0.nl.html
  version: 1.0.0
externalDocs:
  description: Find out more about AERIUS
  url: https://aerius.nl
servers:
- url: TODO
tags:
- name: version
  description: Information about the different versions
- name: sectors
  description: Sector specific information
- name: farming
  description: Farm specific information
paths:
  /sectors:
    get:
      summary: List all sectors
      operationId: listSectors
      tags:
        - sectors
      parameters:
        - name: version
          in: query
          description: Which version to retrieve sectors for.
          required: false
          schema:
            type: string
            default: LATEST
      responses:
        200:
          description: An array of sectors
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Sectors"
        406:
          description: Supplied version not valid.
          content: {}
components:
  schemas:
    Sector:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
    Sectors:
      type: array
      items:
        $ref: "#/components/schemas/Sector"
