openapi: 3.0.1
info:
  title: AERIUS emission service
  description: 'This is a service to retrieve AERIUS emission factors for different sectors'
  license:
    name: GNU Affero General Public License v3.0
    url: https://www.gnu.org/licenses/agpl-3.0.nl.html
  version: 1.0.0
externalDocs:
  description: Find out more about AERIUS
  url: https://aerius.nl/
servers:
- url: http://localhost:8080/
tags:
- name: dataset
  description: Information about the different datasets
- name: sectors
  description: Sector specific information
- name: farming
  description: Farm specific information
paths:
  /datasets:
    get:
      summary: List all datasets
      operationId: listDatasets
      tags:
        - dataset
      responses:
        200:
          description: An array of datasets
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /datasets/{dataset}/sectors:
    get:
      summary: List all sectors
      operationId: listSectors
      tags:
        - sectors
      parameters:
        - name: dataset
          in: path
          description: Which dataset to retrieve sectors for.
          required: true
          schema:
            type: string
            default: LATEST
      responses:
        200:
          description: An array of sectors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Sector"
        404:
          description: Supplied dataset not found.
          content: {}
components:
  schemas:
    Sector:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
